import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import { ArrowLeft, PackageCheck, Plus, Search, X } from 'lucide-react';
import { apiRequest } from '../../lib/api';

type Role = 'admin' | 'manager' | 'staff' | 'technician' | 'viewer';
type Product = { id: string; sku: string; barcode?: string | null; name: string; priceCents: number; stock: number; active: boolean };
type Client = { id: string; name: string; phone: string };
type PaymentMethod = 'cash' | 'transfer' | 'card';
type LayawayListItem = { id: string; folio: string; customerName: string; totalCents: number; paidCents: number; balanceCents: number; status: 'open' | 'paid' | 'delivered' | 'cancelled' | 'expired'; dueAt: string | null; createdAt: string };
type LayawayDetail = LayawayListItem & { customerPhone: string; notes: string | null; items: Array<{ id: string; productNameSnapshot: string; quantity: number; unitPriceCents: number; subtotalCents: number }>; payments: Array<{ id: string; method: PaymentMethod; amountCents: number; createdAt: string; voidedAt: string | null }> };
type CartItem = Product & { quantity: number };

const money = (cents: number, currency: string) => new Intl.NumberFormat('es-MX', { style: 'currency', currency }).format(cents / 100);
const date = (value: string) => new Intl.DateTimeFormat('es-MX', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value));
const paymentLabels: Record<PaymentMethod, string> = { cash: 'Efectivo', transfer: 'Transferencia', card: 'Tarjeta' };
const statusLabels: Record<LayawayListItem['status'], string> = { open: 'Pendiente', paid: 'Liquidado', delivered: 'Entregado', cancelled: 'Cancelado', expired: 'Vencido' };

export function LayawayViews({ token, role, currency }: { token: string; role: Role; currency: string }) {
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [creating, setCreating] = useState(false);
  if (selectedId) return <LayawayDetailView token={token} role={role} currency={currency} id={selectedId} onBack={() => setSelectedId(null)} />;
  if (creating) return <NewLayawayView token={token} currency={currency} onBack={() => setCreating(false)} onCreated={(id) => { setCreating(false); setSelectedId(id); }} />;
  return <LayawayListView token={token} currency={currency} canCreate={['admin', 'manager', 'staff'].includes(role)} onCreate={() => setCreating(true)} onOpen={setSelectedId} />;
}

function LayawayListView({ token, currency, canCreate, onCreate, onOpen }: { token: string; currency: string; canCreate: boolean; onCreate: () => void; onOpen: (id: string) => void }) {
  const [items, setItems] = useState<LayawayListItem[]>([]); const [search, setSearch] = useState(''); const [error, setError] = useState('');
  useEffect(() => { const timeout = window.setTimeout(() => { void apiRequest<{ items: LayawayListItem[] }>(`/api/operations/layaways?search=${encodeURIComponent(search)}`, {}, token).then((result) => setItems(result.items)).catch((reason) => setError(reason instanceof Error ? reason.message : 'No fue posible cargar los apartados.')); }, 250); return () => window.clearTimeout(timeout); }, [search, token]);
  return <section className="sales-history"><div className="pos-section-head"><div><p className="panel-eyebrow">Mercancía reservada</p><h2>Apartados</h2></div>{canCreate && <button className="panel-primary compact-action" onClick={onCreate}><Plus />Nuevo apartado</button>}</div><label className="pos-search"><Search /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Folio o cliente" /></label>{error && <p className="panel-alert">{error}</p>}<div className="sales-list"><div className="sale-history-head"><span>Folio / fecha</span><span>Cliente</span><span>Pagado</span><span>Saldo</span><span>Estado</span></div>{items.map((item) => <button className="sale-history-row" key={item.id} onClick={() => onOpen(item.id)}><div><b>{item.folio}</b><small>{date(item.createdAt)}</small></div><span>{item.customerName}</span><span>{money(item.paidCents, currency)}</span><strong>{money(item.balanceCents, currency)}</strong><em className={item.status === 'cancelled' ? 'sale-cancelled' : 'sale-completed'}>{statusLabels[item.status]}</em></button>)}</div>{!items.length && !error && <p className="empty-state">No hay apartados registrados.</p>}</section>;
}

function NewLayawayView({ token, currency, onBack, onCreated }: { token: string; currency: string; onBack: () => void; onCreated: (id: string) => void }) {
  const [products, setProducts] = useState<Product[]>([]); const [clients, setClients] = useState<Client[]>([]); const [cart, setCart] = useState<CartItem[]>([]); const [search, setSearch] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  useEffect(() => { void Promise.all([apiRequest<{ items: Product[] }>('/api/operations/products?limit=100', {}, token), apiRequest<{ items: Client[] }>('/api/operations/clients?limit=100', {}, token)]).then(([productResult, clientResult]) => { setProducts(productResult.items.filter((item) => item.active)); setClients(clientResult.items); }).catch((reason) => setError(reason instanceof Error ? reason.message : 'No fue posible cargar el catálogo.')); }, [token]);
  const visible = useMemo(() => products.filter((product) => `${product.name} ${product.sku} ${product.barcode ?? ''}`.toLowerCase().includes(search.toLowerCase())), [products, search]);
  const total = cart.reduce((sum, item) => sum + item.priceCents * item.quantity, 0);
  function add(product: Product) { if (!product.stock) return; setCart((current) => current.some((item) => item.id === product.id) ? current.map((item) => item.id === product.id ? { ...item, quantity: Math.min(item.stock, item.quantity + 1) } : item) : [...current, { ...product, quantity: 1 }]); }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(''); const form = new FormData(event.currentTarget); const initialAmount = Math.round(Number(form.get('initialAmount') || 0) * 100); try { const result = await apiRequest<{ item: { id: string } }>('/api/operations/layaways', { method: 'POST', body: JSON.stringify({ customerId: form.get('customerId'), discountCents: 0, dueAt: form.get('dueAt') ? new Date(String(form.get('dueAt'))).toISOString() : null, notes: form.get('notes') || null, items: cart.map((item) => ({ productId: item.id, quantity: item.quantity })), initialPayment: initialAmount > 0 ? { method: form.get('method'), amountCents: initialAmount } : null }) }, token); onCreated(result.item.id); } catch (reason) { setError(reason instanceof Error ? reason.message : 'No fue posible crear el apartado.'); } finally { setBusy(false); } }
  return <div className="pos-shell"><section className="product-shelf"><button className="text-action back-action" onClick={onBack}><ArrowLeft />Apartados</button><div className="pos-section-head"><div><p className="panel-eyebrow">Nueva reserva</p><h2>Selecciona productos</h2></div></div><label className="pos-search"><Search /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Nombre o SKU" /></label><div className="product-pick-grid">{visible.map((product) => <button className="product-pick" key={product.id} disabled={!product.stock} onClick={() => add(product)}><span>{product.sku}</span><b>{product.name}</b><strong>{money(product.priceCents, currency)}</strong><small>{product.stock} disponibles</small><Plus /></button>)}</div></section><aside className="cart-receipt"><div className="receipt-heading"><span>Productos reservados</span><b>{cart.length}</b></div><div className="cart-lines">{cart.map((item) => <article key={item.id}><div><b>{item.name}</b><small>{money(item.priceCents, currency)}</small></div><input aria-label={`Cantidad de ${item.name}`} type="number" min="1" max={item.stock} value={item.quantity} onChange={(event) => setCart((current) => current.map((line) => line.id === item.id ? { ...line, quantity: Math.max(1, Math.min(line.stock, Number(event.target.value))) } : line))} /><strong>{money(item.priceCents * item.quantity, currency)}</strong><button className="remove-line" onClick={() => setCart((current) => current.filter((line) => line.id !== item.id))}><X /></button></article>)}</div><form className="checkout-form" onSubmit={submit}><label>Cliente<select name="customerId" required><option value="">Selecciona</option>{clients.map((client) => <option key={client.id} value={client.id}>{client.name} · {client.phone}</option>)}</select></label><label>Fecha límite<input name="dueAt" type="date" /></label><div className="checkout-fields"><label>Anticipo<input name="initialAmount" type="number" min="0" max={total / 100} step=".01" defaultValue="0" /></label><label>Método<select name="method"><option value="cash">Efectivo</option><option value="transfer">Transferencia</option><option value="card">Tarjeta</option></select></label></div><label>Notas<input name="notes" maxLength={1000} /></label>{error && <p className="form-error">{error}</p>}<div className="cart-total"><span>Total</span><b>{money(total, currency)}</b></div><button className="panel-primary confirm-sale" disabled={!cart.length || busy}>{busy ? 'Reservando…' : 'Crear apartado'}</button></form></aside></div>;
}

function LayawayDetailView({ token, role, currency, id, onBack }: { token: string; role: Role; currency: string; id: string; onBack: () => void }) {
  const [item, setItem] = useState<LayawayDetail | null>(null); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  const load = useCallback(() => apiRequest<{ item: LayawayDetail }>(`/api/operations/layaways/${id}`, {}, token).then((result) => setItem(result.item)).catch((reason) => setError(reason instanceof Error ? reason.message : 'No fue posible cargar el apartado.')), [id, token]);
  useEffect(() => { void load(); }, [load]);
  async function action(path: string, body?: unknown) { setBusy(true); setError(''); setMessage(''); try { const result = await apiRequest<{ item: { cashWarning?: string | null } }>(`/api/operations/layaways/${id}${path}`, { method: 'POST', body: body ? JSON.stringify(body) : undefined }, token); setMessage(result.item.cashWarning ?? 'Operación registrada.'); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'No fue posible completar la operación.'); } finally { setBusy(false); } }
  async function pay(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); await action('/payments', { method: form.get('method'), amountCents: Math.round(Number(form.get('amount')) * 100) }); event.currentTarget.reset(); }
  if (!item) return <div className="panel-loading">{error || 'Cargando apartado…'}</div>;
  const canOperate = ['admin', 'manager', 'staff'].includes(role); const canManage = ['admin', 'manager'].includes(role);
  return <div className="sale-detail-layout"><aside className="sale-actions-panel"><button className="text-action back-action" onClick={onBack}><ArrowLeft />Apartados</button><h2>{item.folio}</h2><span className={item.status === 'cancelled' ? 'sale-cancelled' : 'sale-completed'}>{statusLabels[item.status]}</span><p>{item.customerName}<br />{item.customerPhone}</p><strong>Saldo {money(item.balanceCents, currency)}</strong>{canOperate && item.status === 'open' && <form className="cancel-sale-form" onSubmit={pay}><label>Nuevo abono<input name="amount" type="number" min=".01" max={item.balanceCents / 100} step=".01" required /></label><label>Método<select name="method"><option value="cash">Efectivo</option><option value="transfer">Transferencia</option><option value="card">Tarjeta</option></select></label><button disabled={busy}>Registrar abono</button></form>}{canOperate && item.status === 'paid' && <button className="panel-primary" disabled={busy} onClick={() => void action('/deliver')}><PackageCheck />Marcar entregado</button>}{canManage && ['open', 'paid'].includes(item.status) && <button disabled={busy} onClick={() => { const reason = window.prompt('Motivo de cancelación'); if (reason && reason.trim().length >= 3) void action('/cancel', { reason }); }}>Cancelar apartado</button>}{message && <p className="panel-alert">{message}</p>}{error && <p className="form-error">{error}</p>}</aside><article className="print-ticket"><header><h1>Apartado {item.folio}</h1><p>{item.customerName}</p></header><div className="ticket-meta"><span>Creado <b>{date(item.createdAt)}</b></span>{item.dueAt && <span>Fecha límite <b>{date(item.dueAt)}</b></span>}</div><div className="ticket-items">{item.items.map((line) => <div key={line.id}><span><b>{line.quantity} ×</b> {line.productNameSnapshot}</span><strong>{money(line.subtotalCents, currency)}</strong></div>)}</div><div className="ticket-totals"><strong>Total <b>{money(item.totalCents, currency)}</b></strong><span>Pagado <b>{money(item.paidCents, currency)}</b></span><span>Saldo <b>{money(item.balanceCents, currency)}</b></span></div><section><h3>Abonos</h3>{item.payments.filter((row) => !row.voidedAt).map((row) => <p key={row.id}>{date(row.createdAt)} · {paymentLabels[row.method]} · {money(row.amountCents, currency)}</p>)}</section>{item.notes && <p>{item.notes}</p>}</article></div>;
}
