import cors from 'cors';
import express from 'express';
import helmet from 'helmet';
import { env } from './config/env.js';
import { errorHandler } from './middlewares/error-handler.js';
import { authRouter } from './modules/auth/auth.routes.js';
import { operationsRouter } from './modules/operations/operations.routes.js';
import { publicRouter } from './modules/public/public.routes.js';
import { businessSettingsRouter } from './modules/settings/business-settings.routes.js';
import { salesRouter } from './modules/sales/sales.routes.js';
import { inventoryRouter } from './modules/inventory/inventory.routes.js';
const app = express();
app.disable('x-powered-by');
app.use(helmet());
app.use(cors({ origin: env.APP_URL, credentials: true }));
app.use(express.json({ limit: '100kb' }));
app.get('/health', (_request, response) => response.json({ status: 'ok', service: 'localpos-api' }));
app.use('/api/public', publicRouter);
app.use('/api/auth', authRouter);
app.use('/api/operations/business-settings', businessSettingsRouter);
app.use('/api/operations/sales', salesRouter);
app.use('/api/operations/inventory-movements', inventoryRouter);
app.use('/api/operations', operationsRouter);
app.use(errorHandler);
app.listen(env.PORT, () => console.log(`LocalPOS API disponible en http://localhost:${env.PORT}`));
