import { FormEvent, useCallback, useEffect, useState } from 'react';
import { Boxes, ClipboardList, History, LayoutDashboard, LogOut, PackagePlus, Search, Settings, ShieldCheck, ShoppingCart, Store, UserPlus, Users, Wrench } from 'lucide-react';
import { apiRequest } from '../lib/api';
import { QuickSaleView, SaleDetailView, SalesHistoryView } from '../modules/sales/SalesViews';
import '../styles/panel.css';

type Section = 'dashboard' | 'clients' | 'products' | 'repairs' | 'sales' | 'sales-history' | 'sale-detail' | 'settings';
type Client = { id:string; name:string; phone:string; email:string|null; notes:string|null };
type Product = { id:string; sku:string; name:string; priceCents:number; stock:number; minimumStock:number; active:boolean };
type Repair = { id:string; folio:string; clientId:string; clientName:string; clientPhone:string; brand:string; model:string; status:string; reportedIssue:string; depositCents:number };
type Summary = { clients:number; products:number; openRepairs:number; readyRepairs:number; lowStock:number };
type BusinessSettings = { id:string; businessName:string; businessType:string; logoUrl:string|null; phone:string|null; address:string|null; city:string|null; state:string|null; ticketMessage:string|null; warrantyMessage:string|null; currency:string; primaryColor:string; updatedAt:string };
type Role = 'admin' | 'technician';
const TOKEN='cellab-panel-token';
function sectionFromPath():Section { const path=window.location.pathname; if(/^\/panel\/ventas\/[^/]+$/.test(path)&&path!=='/panel/ventas/historial')return 'sale-detail'; if(path==='/panel/ventas/historial')return 'sales-history'; if(path==='/panel/ventas')return 'sales'; if(path==='/panel/configuracion')return 'settings'; return 'dashboard'; }
function sectionPath(section:Section){ if(section==='sales')return '/panel/ventas';if(section==='sales-history')return '/panel/ventas/historial';if(section==='settings')return '/panel/configuracion';return '/panel'; }
function currentSaleId(){return window.location.pathname.split('/').pop()??'';}
const money=(c:number,currency='MXN')=>new Intl.NumberFormat('es-MX',{style:'currency',currency}).format(c/100);
function tokenRole(token:string):Role { try { const part=token.split('.')[1]??''; const payload=JSON.parse(atob(part.replace(/-/g,'+').replace(/_/g,'/').padEnd(Math.ceil(part.length/4)*4,'='))); return payload.role==='admin'?'admin':'technician'; } catch { return 'technician'; } }
const statusLabel:Record<string,string>={received:'Recibido',diagnosis:'Diagnóstico',awaiting_authorization:'Por autorizar',in_repair:'En reparación',testing:'En pruebas',ready:'Listo',delivered:'Entregado',cancelled:'Cancelado'};
const states=Object.keys(statusLabel);

export function PanelPage(){
  const [token,setToken]=useState(()=>localStorage.getItem(TOKEN)??'');
  if(!token) return <Login onLogin={(value)=>{localStorage.setItem(TOKEN,value);setToken(value)}}/>;
  return <Panel token={token} onLogout={()=>{localStorage.removeItem(TOKEN);setToken('')}}/>;
}
function Login({onLogin}:{onLogin:(token:string)=>void}){
  const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
  async function submit(event:FormEvent<HTMLFormElement>){
    event.preventDefault(); setBusy(true); setError('');
    const data=new FormData(event.currentTarget);
    try{const result=await apiRequest<{token:string}>('/api/auth/login',{method:'POST',body:JSON.stringify({email:data.get('email'),password:data.get('password')})});onLogin(result.token)}
    catch(e){setError(e instanceof Error?e.message:'No fue posible iniciar sesión.')}finally{setBusy(false)}
  }
  return <main className="panel-login"><section className="login-card"><div className="login-mark"><Store/><span>LOCALPOS / OPERACIONES</span></div><p className="panel-eyebrow">Acceso operativo</p><h1>Tu negocio, listo para operar.</h1><p>Ventas, inventario, clientes y servicios desde una base configurable.</p><form onSubmit={submit}><label>Correo<input name="email" type="email" autoComplete="username" required/></label><label>Contraseña<input name="password" type="password" autoComplete="current-password" required/></label>{error&&<p className="form-error">{error}</p>}<button className="panel-primary" disabled={busy}>{busy?'Verificando…':'Entrar al panel'}</button></form><small><ShieldCheck/> Sesión protegida y acciones registradas.</small></section></main>;
}
function Panel({token,onLogout}:{token:string;onLogout:()=>void}){
  const [section,setSection]=useState<Section>(sectionFromPath); const [summary,setSummary]=useState<Summary|null>(null);
  const [business,setBusiness]=useState<BusinessSettings|null>(null); const role=tokenRole(token);
  const [clients,setClients]=useState<Client[]>([]); const [products,setProducts]=useState<Product[]>([]); const [repairs,setRepairs]=useState<Repair[]>([]);
  const [error,setError]=useState(''); const [busy,setBusy]=useState(false); const [search,setSearch]=useState('');
  const loadBusiness=useCallback(async()=>{try{const data=await apiRequest<{item:BusinessSettings}>('/api/operations/business-settings',{},token);setBusiness(data.item)}catch(e){setError(e instanceof Error?e.message:'No fue posible cargar la configuración.')}},[token]);
  useEffect(()=>{void loadBusiness()},[loadBusiness]);
  useEffect(()=>{const sync=()=>setSection(sectionFromPath());window.addEventListener('popstate',sync);return()=>window.removeEventListener('popstate',sync)},[]);
  const load=useCallback(async()=>{
    setBusy(true);setError('');
    try{
      if(section==='dashboard')setSummary(await apiRequest<Summary>('/api/operations/dashboard',{},token));
      if(section==='clients')setClients((await apiRequest<{items:Client[]}>(`/api/operations/clients?search=${encodeURIComponent(search)}`,{},token)).items);
      if(section==='products')setProducts((await apiRequest<{items:Product[]}>(`/api/operations/products?search=${encodeURIComponent(search)}`,{},token)).items);
      if(section==='repairs'){const [r,c]=await Promise.all([apiRequest<{items:Repair[]}>(`/api/operations/repairs?search=${encodeURIComponent(search)}`,{},token),apiRequest<{items:Client[]}>('/api/operations/clients?limit=100',{},token)]);setRepairs(r.items);setClients(c.items)}
    }catch(e){const m=e instanceof Error?e.message:'No fue posible cargar los datos.';setError(m);if(m.toLowerCase().includes('sesión'))onLogout()}finally{setBusy(false)}
  },[section,search,token,onLogout]);
  useEffect(()=>{void load()},[load]);
  const navigate=(next:Section,path=sectionPath(next))=>{window.history.pushState({},'',path);setSection(next)};
  const nav:[Section,string,typeof LayoutDashboard][]=[['dashboard','Resumen operativo',LayoutDashboard],['sales','Venta rápida',ShoppingCart],['sales-history','Historial de ventas',History],['clients','Clientes',Users],['products','Inventario',Boxes],['repairs','Reparaciones',ClipboardList],['settings','Configuración',Settings]];
  return <main className="panel-root" style={{'--ops-blue':business?.primaryColor??'#185a70'} as React.CSSProperties}><aside className="panel-sidebar"><a className="panel-brand" href="/"><span>LP</span><b>LocalPOS<small>{business?.businessName??'Negocio local'}</small></b></a><nav>{nav.map(([key,label,Icon])=><button key={key} className={section===key?'active':''} onClick={()=>{setSearch('');navigate(key)}}><Icon/>{label}</button>)}</nav><button className="panel-logout" onClick={onLogout}><LogOut/>Cerrar sesión</button></aside><section className="panel-workspace"><header><div><p className="panel-eyebrow">LocalPOS / {business?.businessName??'Configurando negocio'}</p><h1>{section==='sale-detail'?'Detalle de venta':nav.find(([key])=>key===section)?.[1]}</h1></div>{!['dashboard','settings','sales','sales-history','sale-detail'].includes(section)&&<label className="panel-search"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar en este módulo…"/></label>}</header>{error&&<div className="panel-alert">{error}<button onClick={()=>void load()}>Reintentar</button></div>}{busy&&<div className="panel-loading">Sincronizando operación…</div>}{!busy&&section==='dashboard'&&<Dashboard summary={summary}/>} {!busy&&section==='clients'&&<Clients token={token} items={clients} reload={load}/>} {!busy&&section==='products'&&<Products token={token} items={products} reload={load} currency={business?.currency??'MXN'}/>} {!busy&&section==='repairs'&&<Repairs token={token} items={repairs} clients={clients} reload={load}/>} {!busy&&section==='sales'&&business&&<QuickSaleView token={token} business={business} onOpenSale={(id)=>navigate('sale-detail','/panel/ventas/'+id)} onOpenHistory={()=>navigate('sales-history')}/>} {!busy&&section==='sales-history'&&business&&<SalesHistoryView token={token} business={business} onOpenSale={(id)=>navigate('sale-detail','/panel/ventas/'+id)} onNewSale={()=>navigate('sales')}/>} {!busy&&section==='sale-detail'&&<SaleDetailView token={token} saleId={currentSaleId()} role={role} onBack={()=>navigate('sales-history')}/>} {!busy&&section==='settings'&&business&&<BusinessConfiguration token={token} item={business} role={role} onSaved={loadBusiness}/>}</section></main>;
}
function Dashboard({summary}:{summary:Summary|null}){
  if(!summary)return null;const metrics=[['Equipos activos',summary.openRepairs,'En flujo'],['Listos para entregar',summary.readyRepairs,'Cobrar y cerrar'],['Stock crítico',summary.lowStock,'Reponer'],['Clientes',summary.clients,'Historial'],['Productos',summary.products,'Catálogo']];
  return <div className="ops-dashboard"><section className="queue-card"><p>Prioridad de recepción</p><strong>{summary.openRepairs}</strong><h2>equipos siguen en mesa</h2><span>El siguiente movimiento debe quedar registrado en el folio.</span></section><div className="metric-list">{metrics.map(([label,value,note])=><article key={String(label)}><span>{label}</span><b>{value}</b><small>{note}</small></article>)}</div></div>;
}
function Clients({token,items,reload}:{token:string;items:Client[];reload:()=>Promise<void>}){
  const [edit,setEdit]=useState<Client|null>(null);
  async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),body={name:f.get('name'),phone:f.get('phone'),email:f.get('email')||null,notes:f.get('notes')||null};await apiRequest(edit?`/api/operations/clients/${edit.id}`:'/api/operations/clients',{method:edit?'PATCH':'POST',body:JSON.stringify(body)},token);setEdit(null);e.currentTarget.reset();await reload()}
  async function remove(id:string){if(!confirm('¿Archivar este cliente? Su historial se conservará.'))return;await apiRequest(`/api/operations/clients/${id}`,{method:'DELETE'},token);await reload()}
  return <ModuleLayout title={edit?'Editar cliente':'Registrar cliente'} icon={<UserPlus/>} form={<form className="ops-form" onSubmit={save} key={edit?.id??'new'}><label>Nombre<input name="name" defaultValue={edit?.name} required/></label><label>Teléfono<input name="phone" defaultValue={edit?.phone} required/></label><label>Correo<input name="email" type="email" defaultValue={edit?.email??''}/></label><label className="wide">Notas<textarea name="notes" defaultValue={edit?.notes??''}/></label><div className="form-actions">{edit&&<button type="button" onClick={()=>setEdit(null)}>Cancelar</button>}<button className="panel-primary">Guardar cliente</button></div></form>}><DataTable empty="Aún no hay clientes. Registra el primero.">{items.map(x=><div className="data-row client-row" key={x.id}><div><b>{x.name}</b><span>{x.phone}</span></div><span>{x.email??'Sin correo'}</span><div className="row-actions"><button onClick={()=>setEdit(x)}>Editar</button><button onClick={()=>void remove(x.id)}>Archivar</button></div></div>)}</DataTable></ModuleLayout>;
}
function Products({token,items,reload,currency}:{token:string;items:Product[];reload:()=>Promise<void>;currency:string}){
  const [edit,setEdit]=useState<Product|null>(null);
  async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),body={sku:f.get('sku'),name:f.get('name'),priceCents:Math.round(Number(f.get('price'))*100),stock:Number(f.get('stock')),minimumStock:Number(f.get('minimumStock')),active:true};await apiRequest(edit?`/api/operations/products/${edit.id}`:'/api/operations/products',{method:edit?'PATCH':'POST',body:JSON.stringify(body)},token);setEdit(null);await reload()}
  async function remove(id:string){if(!confirm('¿Archivar este producto?'))return;await apiRequest(`/api/operations/products/${id}`,{method:'DELETE'},token);await reload()}
  return <ModuleLayout title={edit?'Editar producto':'Alta de inventario'} icon={<PackagePlus/>} form={<form className="ops-form" onSubmit={save} key={edit?.id??'new'}><label>SKU<input name="sku" defaultValue={edit?.sku} required/></label><label>Producto<input name="name" defaultValue={edit?.name} required/></label><label>Precio MXN<input name="price" type="number" step=".01" min="0" defaultValue={edit?edit.priceCents/100:''} required/></label><label>Existencia<input name="stock" type="number" min="0" defaultValue={edit?.stock??0} required/></label><label>Stock mínimo<input name="minimumStock" type="number" min="0" defaultValue={edit?.minimumStock??0} required/></label><div className="form-actions">{edit&&<button type="button" onClick={()=>setEdit(null)}>Cancelar</button>}<button className="panel-primary">Guardar producto</button></div></form>}><DataTable empty="El inventario está vacío."><div className="data-head product-row"><span>Producto</span><span>Precio</span><span>Stock</span><span>Acciones</span></div>{items.map(x=><div className="data-row product-row" key={x.id}><div><b>{x.name}</b><span>{x.sku}</span></div><b>{money(x.priceCents,currency)}</b><span className={x.stock<=x.minimumStock?'stock-low':''}>{x.stock} pzas.</span><div className="row-actions"><button onClick={()=>setEdit(x)}>Editar</button><button onClick={()=>void remove(x.id)}>Archivar</button></div></div>)}</DataTable></ModuleLayout>;
}
function Repairs({token,items,clients,reload}:{token:string;items:Repair[];clients:Client[];reload:()=>Promise<void>}){
  async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),body={clientId:f.get('clientId'),brand:f.get('brand'),model:f.get('model'),reportedIssue:f.get('reportedIssue'),physicalCondition:f.get('physicalCondition'),depositCents:Math.round(Number(f.get('deposit'))*100)};await apiRequest('/api/operations/repairs',{method:'POST',body:JSON.stringify(body)},token);e.currentTarget.reset();await reload()}
  async function move(id:string,status:string){await apiRequest(`/api/operations/repairs/${id}/status`,{method:'PATCH',body:JSON.stringify({status})},token);await reload()}
  return <ModuleLayout title="Recibir un equipo" icon={<Wrench/>} form={<form className="ops-form repair-form" onSubmit={save}><label>Cliente<select name="clientId" required><option value="">Selecciona…</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name} · {c.phone}</option>)}</select></label><label>Marca<input name="brand" required/></label><label>Modelo<input name="model" required/></label><label>Anticipo MXN<input name="deposit" type="number" min="0" step=".01" defaultValue="0"/></label><label className="wide">Falla reportada<textarea name="reportedIssue" required/></label><label className="wide">Condición física al recibir<textarea name="physicalCondition" required/></label><div className="form-actions"><button className="panel-primary">Crear folio de reparación</button></div></form>}><DataTable empty="No hay reparaciones registradas.">{items.map(x=><div className="repair-ticket" key={x.id}><div className="ticket-folio"><small>Folio</small><b>{x.folio}</b></div><div><b>{x.brand} {x.model}</b><span>{x.clientName} · {x.clientPhone}</span><p>{x.reportedIssue}</p></div><label>Estado<select value={x.status} onChange={e=>void move(x.id,e.target.value)}>{states.map(s=><option value={s} key={s}>{statusLabel[s]}</option>)}</select></label><span className={`status-dot status-${x.status}`}>{statusLabel[x.status]}</span></div>)}</DataTable></ModuleLayout>;
}
function BusinessConfiguration({token,item,role,onSaved}:{token:string;item:BusinessSettings;role:Role;onSaved:()=>Promise<void>}){
  const [message,setMessage]=useState(''); const [saving,setSaving]=useState(false); const canEdit=role==='admin';
  async function save(event:FormEvent<HTMLFormElement>){
    event.preventDefault(); if(!canEdit)return; setSaving(true);setMessage('');
    const form=new FormData(event.currentTarget); const value=(name:string)=>String(form.get(name)??'').trim()||null;
    const body={businessName:value('businessName'),businessType:value('businessType'),logoUrl:value('logoUrl'),phone:value('phone'),address:value('address'),city:value('city'),state:value('state'),ticketMessage:value('ticketMessage'),warrantyMessage:value('warrantyMessage'),currency:String(form.get('currency')??'MXN'),primaryColor:String(form.get('primaryColor')??'#0A84FF')};
    try{await apiRequest('/api/operations/business-settings',{method:'PATCH',body:JSON.stringify(body)},token);await onSaved();setMessage('Configuración guardada. Los próximos tickets usarán estos datos.')}
    catch(e){setMessage(e instanceof Error?e.message:'No fue posible guardar la configuración.')}finally{setSaving(false)}
  }
  return <div className="settings-grid"><section className="settings-form-card"><div className="settings-intro"><div><p className="panel-eyebrow">Identidad del negocio</p><h2>Datos operativos y de impresión</h2></div><span className={canEdit?'role-chip role-admin':'role-chip'}>{canEdit?'Admin · edición habilitada':'Technician · solo lectura'}</span></div><form className="ops-form settings-form" onSubmit={save} key={item.updatedAt}><label>Nombre comercial<input name="businessName" defaultValue={item.businessName} disabled={!canEdit} required/></label><label>Tipo de negocio<input name="businessType" defaultValue={item.businessType} disabled={!canEdit} required/></label><label>Teléfono<input name="phone" defaultValue={item.phone??''} disabled={!canEdit}/></label><label>Moneda<input name="currency" defaultValue={item.currency} maxLength={3} disabled={!canEdit} required/></label><label className="wide">Dirección<input name="address" defaultValue={item.address??''} disabled={!canEdit}/></label><label>Ciudad<input name="city" defaultValue={item.city??''} disabled={!canEdit}/></label><label>Estado<input name="state" defaultValue={item.state??''} disabled={!canEdit}/></label><label className="wide">URL del logotipo<input name="logoUrl" type="url" defaultValue={item.logoUrl??''} disabled={!canEdit} placeholder="https://…"/></label><label>Color principal<input name="primaryColor" type="color" defaultValue={item.primaryColor} disabled={!canEdit}/></label><label className="wide">Mensaje para tickets<textarea name="ticketMessage" defaultValue={item.ticketMessage??''} disabled={!canEdit}/></label><label className="wide">Mensaje de garantía<textarea name="warrantyMessage" defaultValue={item.warrantyMessage??''} disabled={!canEdit}/></label>{message&&<p className="settings-message wide">{message}</p>}{canEdit&&<div className="form-actions"><button className="panel-primary" disabled={saving}>{saving?'Guardando…':'Guardar configuración'}</button></div>}</form></section><aside className="business-preview" style={{'--preview-color':item.primaryColor} as React.CSSProperties}><p>Vista para notas</p><div className="preview-logo">{item.logoUrl?<img src={item.logoUrl} alt="Logotipo configurado"/>:<span>LP</span>}</div><h3>{item.businessName}</h3><small>{item.businessType}</small><address>{[item.address,item.city,item.state].filter(Boolean).join(' · ')}</address><b>{item.phone}</b><div className="preview-rule"/><p>{item.ticketMessage}</p><em>{item.warrantyMessage}</em><footer>{item.currency} · Datos administrados por LocalPOS</footer></aside></div>;
}

function ModuleLayout({title,icon,form,children}:{title:string;icon:React.ReactNode;form:React.ReactNode;children:React.ReactNode}){return <div className="module-grid"><aside className="capture-panel"><h2>{icon}{title}</h2>{form}</aside><section className="records-panel">{children}</section></div>}
function DataTable({empty,children}:{empty:string;children:React.ReactNode}){return <div className="data-table">{Array.isArray(children)&&children.length===0?<p className="empty-state">{empty}</p>:children}</div>}
